FFP/Models/ErrorViewModel.cs
namespace FFP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FFP/Models/Jogador.cs
namespace FFP.Models
{
    public class Jogador
    {
        Random random= new Random();
        public Jogador()
        {

        }
        public Jogador(int id, string nome, string posicao, int idade, string peDominante, string endereco)
        {
            Id = id;
            Nome = nome;
            Posicao = posicao;
            Idade = idade;
            PeDominante = peDominante;
            Endereco = endereco;
            TimeID = random.Next();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Posicao { get; set; }
        public int Idade { get; set; }
        public string PeDominante { get; set; }
        public string Endereco { get; set; }
        public int TimeID { get; set; }
        public Time Time { get; set; }
    }
}

FFP/Models/Time.cs
using System.IO;

namespace FFP.Models
{
    public class Time
    {
        Random random = new Random();
        public Time()
        {

        }
        public Time(int id, string nome, string bairro, DateTime fundacao, string presidente)
        {
            Id = id;
            Nome = nome;
            Bairro = bairro;
            Fundacao = fundacao;
            Presidente = presidente;
            JogadorID = random.Next();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Bairro { get; set; }
        public DateTime Fundacao { get; set; }
        public string Presidente { get; set; }
        public int JogadorID { get; set; }
        public virtual ICollection<Jogador> Jogadores { get; set; }
    }
}

FFP/Controllers/HomeController.cs
using FFP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FFP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FFP/Controllers/JogadorController.cs
using FFP.Models;
using FFP.Services;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace FFP.Controllers
{
    public class JogadorController : Controller
    {
        private readonly JogadorService _jogadorService;

        public JogadorController(JogadorService jogadorService)
        {
            _jogadorService= jogadorService;
        }
        public async Task<IActionResult> Index()
        {
            var listJogadores = await _jogadorService.GetJogadores();
            return View(listJogadores);
        }

        [HttpPost]

        public async Task<IActionResult> Create(Jogador jogador)
        {
            await _jogadorService.Create(jogador);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return BadRequest("Bad Request!");
            }
            var jogador = await _jogadorService.GetJogadorById(id.Value);
            if(jogador == null)
            {
                return BadRequest("Bad Request!");
            }

            return View(jogador);   
        }

        [HttpPost]

        public async Task<IActionResult> Edit(int id, Jogador jogador)
        {
            if(id != jogador.Id)
            {
                return BadRequest("O id é inválido");
            }

            try
            {
                await _jogadorService.Update(jogador);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                throw;
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Bad Request");
            }

            var obj = await _jogadorService.GetJogadorById(id.Value); // Por ser opcional, precisa usar o "Value"
            if (obj == null)
            {
                return BadRequest("Bad Request");
            }

            return View(obj);
        }

        //Post
        [HttpPost]
        public async Task<IActionResult> Delete(Jogador id)
        {
            try
            {
                await _jogadorService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
        }
    }
}

FFP/Controllers/TimeController.cs
using FFP.Context;
using FFP.Models;
using FFP.Services;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Diagnostics;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace FFP.Controllers
{
    public class TimeController : Controller
    {
        private readonly TimeService _timeService;

        public TimeController(TimeService timeService)
        {
            _timeService = timeService;
        }
        public async Task<IActionResult> Index()
        {
            var list = await _timeService.GetTimes();
            return View(list);
        }


        /*public async Task<IActionResult> Create()
        {
            var departments = await _departmentService.FindAllAsync();
            var viewModel = new SellerFormViewModel { Departments = departments };
            return View(viewModel);

                Modificar quando for carregar jogadores
        }
        */
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Time time)
        {
            await _timeService.Create(time);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest("Bad Request");

            }

            var obj = await _timeService.GetTimeById(id.Value);
            if (obj == null)
            {
                return BadRequest("Bad Request");
            }

            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Time time)
        {
            if (id != time.Id) // Valida o id recebido, ou se tem a tabela no DB
            {
                return BadRequest("Bad Request");
            }
            try
            {
                await _timeService.Update(time);
                return RedirectToAction(nameof(Index));
            }
            catch (ApplicationException e)
            {
                throw;
            }
        }

        //GET: Time/Delete/id
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest("Bad Request");
            }

            var obj = await _timeService.GetTimeById(id.Value); // Por ser opcional, precisa usar o "Value"
            if (obj == null)
            {
                return BadRequest("Bad Request");
            }

            return View(obj);
        }

        //Post
        [HttpPost]
        public async Task<IActionResult> Delete(Time id)
        {
            try
            {
                await _timeService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
        }

    }
}

FFP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FFP/Views/Jogador/Index.cshtml
@model IEnumerable<FFP.Models.Jogador>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
        }
    </tbody>
</table>

FFP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FFP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cyborg.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FFP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FFP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Time" asp-action="Index">Time</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jogador" asp-action="Index">Jogador</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FFP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FFP/Views/Time/Create.cshtml
@model FFP.Models.Time

@{
    ViewData["Title"] = "Times Cadastrados";
}

<h2>@ViewData["Title"]</h2>
<div class="row">
    <div class="col-md-6">
        <form class="form-horizontal" asp-action="Create">
            <fieldset>
                <legend>Criar</legend>
                <div class="form-group">
                    <label for="Nome" class="col-lg-2 control-label">Nome</label>
                    <div class="col-lg-10">
                        <input type="text" name="Nome" class="form-control" />
                    </div>
                    <label for="Bairro" class="col-lg-2 control-label">Bairro</label>
                    <div class="col-lg-10">
                        <input type="text" name="Bairro" class="form-control" />
                    </div>
                    <label for="Fundacao" class="col-lg-2 control-label">Fundacao</label>
                    <div class="col-lg-10">
                        <input type="date" name="Fundacao" class="form-control" />
                    </div>
                    <label for="Presidente" class="col-lg-2 control-label">Presidente</label>
                    <div class="col-lg-10">
                        <input type="text" name="Presidente" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

FFP/Views/Time/Delete.cshtml
@model FFP.Models.Time

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Time</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FFP/Views/Time/Details.cshtml
@model FFP.Models.Time

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Time</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FFP/Views/Time/Edit.cshtml
@model FFP.Models.Time

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Time</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
                <label asp-for="Fundacao" class="control-label"></label>
                <input asp-for="Fundacao" class="form-control" />
                <span asp-validation-for="Fundacao" class="text-danger"></span>
                <label asp-for="Presidente" class="control-label"></label>
                <input asp-for="Presidente" class="form-control" />
                <span asp-validation-for="Presidente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FFP/Views/Time/Index.cshtml
@model IEnumerable<FFP.Models.Time>

@{
    ViewData["Title"] = "Times Cadastrados";
    ViewData["Message"] = "Cadastre seu time para poder aproveitar as vantagens do Fun Football Players!";

}

<h1>@ViewData["Title"]</h1>
<p>@ViewData["Message"]</p>

<p>
    <a asp-action="Create">Cadastrar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fundacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bairro)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fundacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bairro)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>